sudo: false

language: php

cache:
  directories:
    - "$HOME/.composer/cache/files"

matrix:
  include:
    - php: 5.5
      env:
        - COMPOSER_FLAGS="--prefer-dist --no-interaction" # --prefer-lowest TODO FIXME sulu 1.3 issue
    - php: 7.0
      env:
        - COMPOSER_FLAGS="--prefer-dist --no-interaction"
        - CODE_COVERAGE=true
        - PHPSTAN=true

before_install:
  - composer self-update
  - phpenv config-add Tests/travis.php.ini

install:
  - if [[ $PHPSTAN == 'true' ]]; then travis_retry composer require --dev phpstan/phpstan $COMPOSER_FLAGS ; else travis_retry composer update $COMPOSER_FLAGS ; fi
  - composer info -i
  - ./Tests/app/console doctrine:database:create
  - ./Tests/app/console doctrine:schema:update --force

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover
  - if [[ $PHPSTAN == 'true' ]]; then ./vendor/bin/phpstan analyse ./ --level 1 -c phpstan.neon ; fi

after_script:
  - if [[ $CODE_COVERAGE == 'true' ]]; then wget https://scrutinizer-ci.com/ocular.phar ; fi
  - if [[ $CODE_COVERAGE == 'true' ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover ; fi
